### ISSUE TITLE
TypeError: Cannot read property 'write' of null

### ISSUE THREAD

**Issue by Paul1896** [Microsoft/AzureMonitorAddonForSplunk#125]
Hello,

I hope you can help me with my issue. I already read the threads with the same issue but I didn't solve the problem yet.

```
02-25-2019 15:55:41.318 +0000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at Timer.listOnTimeout (timers.js:214:5)
--
  | 02-25-2019 15:55:41.318 +0000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at tryOnTimeout (timers.js:250:5)
  | 02-25-2019 15:55:41.318 +0000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at ontimeout (timers.js:386:11)
  | 02-25-2019 15:55:41.318 +0000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at Timeout._onTimeout (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/amqp10/lib/link.js:270:12)
  | 02-25-2019 15:55:41.318 +0000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at ReceiverLink.Link.attach (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/amqp10/lib/link.js:152:27)
  | 02-25-2019 15:55:41.318 +0000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at Connection.sendFrame (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/amqp10/lib/connection.js:329:10)
  | 02-25-2019 15:55:41.318 +0000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"     at Object.frames.writeFrame (/opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/amqp10/lib/frames.js:64:9)
  | 02-25-2019 15:55:41.318 +0000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" TypeError: Cannot read property 'write' of null
  | 02-25-2019 15:55:41.318 +0000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"         ^
  | 02-25-2019 15:55:41.318 +0000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh"   stream.write(buffer, callback);
  | 02-25-2019 15:55:41.317 +0000 ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" /opt/splunk/etc/apps/TA-Azure_Monitor/bin/app/node_modules/amqp10/lib/frames.js:64

```

CLI:

```
/opt/splunk/etc/apps/TA-Azure_Monitor/bin>./azure_activity_log.sh
ERROR Modular input Error: Receiving input definitions prior to streaming timed out.
```
Port 5671 and Port 5672 are also open for outbound connections. 

hubs.json contains only one hub which is created with the same name on azure side.

```
{
 "heartbeat": "resourceId"
}
```

Thank you!

**Comment by sebastus** [comment]
how many partitions does the heartbeat hub have? It has to be 4.

**Comment by Paul1896** [comment]
@sebastus Partition count is set to 4.

**Comment by sebastus** [comment]
and the heartbeat hub actually exists in the hub namespace?

**Comment by Paul1896** [comment]
yes only the heartbeat hub exists in the hub namespace and has a partition count of 4

**Comment by sebastus** [comment]
I'll need to take a closer look at this. Please email me:
golive@microsoft.com.

**Comment by sebastus** [comment]
The solution to this is as follows:

The hub name "insights-operational-logs" was listed in hubs.json. There was no log profile to export Activity Log to event hub. The diagnostic logs data input was configured.

There are 3 things wrong with this:
1. "insights-operational-logs" hub is for Activity Logs only. It is created by the platform when the first log is exported. It should never be in hubs.json.
2. because there was no log profile to export Activity logs to event hub, this hub (in #1) did not exist.
3. Because the hub did not exist and the diagnostic logs data input was configured, the data input was trying to read from a nonexistent hub. This is the basis of the error message.

If the log profile existed and therefore the hub existed, the data input would not have complained. But the messages would not be categorized correctly and some errors would be thrown due to differences in the structure of the messages. If the Activity Log data input were also configured, both data inputs would be reading from the same hub - creating a race condition. No errors would occur, but some messages would be indexed strangely due to being processed by the diagnostic logs TA.
