### ISSUE TITLE
Questions on Ingested Data

### ISSUE THREAD

**Issue by bdschaap** [microsoft/AzureMonitorAddonForSplunk#141]
I'm trying to better understand the data being ingested.  For instance, I'm reviewing data for an App Service Plan resource in one of my subscriptions.  The value of _time appears to be the time the add-on polls data or the time it's ingested as opposed to the value of timeStamp.  Is that correct?  It's more common in Splunk to see data indexed by a time field in the contents of the data which in this case would be timeStamp.

I'm also seeing some inconsistencies in the data being ingested.  In my App Service Plan resource, for the Memory Percentage metric I'm seeing data.total recorded for some events and data.average recorded for others.  However, I'm not seeing both aggregations with the same timeStamp.  I made a REST API call myself to see what data is being returned and I am receiving the average aggregation at one minute granularity.  I'm trying to better understand why the add-on isn't ingesting the average aggregation for each of those same events with one minute granularity.  Sometimes total is ingested instead of average.

**Comment by sebastus** [comment]
re: time. the TA doesn't handle time correctly - it should add the time of
the resource event to the metadata of the splunk event. The function
implementation of the TA does this correctly.

re: metrics. Metrics are acquired each time the TA runs, regardless of
whether there's actually anything to get. The TA runs the query, packages
up the results and ships them off to Splunk.

Are you open to taking a look at the function version of the TA? It gets
metrics from the event hub rather than querying the API. I think this is a
more reliable approach.

The most recent updates are in the functionProxy branch. They'll get merged
to master after I've run it a bit more.

https://github.com/microsoft/AzureFunctionforSplunkVS

**Comment by bdschaap** [comment]
I appreciate the feedback.  

Thanks for explaining that the TA doesn't handle time correctly.

I'm having trouble understanding why data.total is ingested sometimes but data.average other times.  When I called the Azure Monitor REST API directly it returned only average.  I didn't specify the aggregate function to return so I believe it uses the default which is average.

I like the REST API approach because it's supported by all Azure resources.  I would consider the Functions / Event Hubs route but currently Azure resources don't have consistent diagnostic settings.  Some don't have these settings (ex - Azure SignalR).  Others such as storage record to a diagnostic blob or table within the storage account.  It will be a better option when there is more consistency across resources.
