### ISSUE TITLE
Microsoft.Azure.Commands.KeyVault.SetAzureKeyVaultAccessPolicy

### ISSUE THREAD

**Issue by ishantshrestha** [microsoft/AzureMonitorAddonForSplunk#165]
.\azure-setup.ps1
Creating resource group '*****' in region 'South India'.
Creating event hub namespace 'spleh**************' in resource group '******'.
Creating Key Vault 'splkv**************' in resource group '*******'.
- Setting default access policy for '**********@onmicrosoft.com'
Set-AzureRmKeyVaultAccessPolicy : Cannot find the Active Directory object '' in tenant
'********-****-****-****-**********'. Please make sure that the user or application service principal you are
authorizing is registered in the current subscription's Azure Active directory. The TenantID displayed by the cmdlet
'Get-AzureRmContext' is the current subscription's Azure Active directory.
At C:\Program Files\Splunk\etc\apps\AzureMonitorAddonForSplunk-master\scripts\azure-setup.ps1:33 char:1
+ Set-AzureRmKeyVaultAccessPolicy -ResourceGroupName $keyVault.Resource ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmKeyVaultAccessPolicy], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.KeyVault.SetAzureKeyVaultAccessPolicy

I am currently using Free Trial version of Microsoft Azure. Please help me with this issue?

**Comment by mythdevishere** [comment]
There's a small change you need to make in the script in the below command. 
Instead of -emailaddress, you need to use -UserPrincipalName as shown below. 

Set-AzureRmKeyVaultAccessPolicy -ResourceGroupName $keyVault.ResourceGroupName -VaultName $keyVault.VaultName -UserPrincipalName $azureSession.Context.Account -PermissionsToSecrets get,list,set,delete,recover,backup,restore -PermissionsToKey get,list,update,create,import,delete,recover,backup,restore
