### ISSUE TITLE
Problem with Azure Metrics 

### ISSUE THREAD

**Issue by KrazyK86** [microsoft/AzureMonitorAddonForSplunk#46]
Hello,
we have a problem with the Metrics input of your Azure Addon for Splunk. For example, we access Redis data from our system in particular "connectedclients". For these, we repeatedly receive "total" data, although this should not exist according to the Azure specification ([https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-supported-metrics#microsoftcacheredis](url)). But again and again we don't get the actual maximum value. Do you have any idea what the problem is here?

**Comment by sebastus** [comment]
"total" is one of the aggregation types available for connectedclients - the complete list is: 
"None", "Average","Minimum", "Maximum", "Total", "Count". "Maximum" is the primary - i.e. the one that should be delivered if no aggregation type is requested. 

The add-on does one request for metrics (to avoid api throttling) and 'or's together all of the requested metrics - with no aggregation type specified because they're invariably different for the different metrics. 

I suspect that the first one in your list of requested metrics has a primary aggregation type of 'total'. Can you check - and perhaps switch the ordering to see if that has any effect?

**Comment by KrazyK86** [comment]
Thanks for the quick answer.
I checked but connectedclients is at the top of the list. The values always vary between total and maximum. I once retrieved the values directly with a Powershell script. Apparently, the first value in the list is always used. So I have changed the input to query both aggregation types.

**Comment by sebastus** [comment]
So - you're saying that connectedclients is at the top of your tags for the cache, and sometimes you get maximum and other times you get total? Changing nothing but waiting for new metrics to arrive?

**Comment by KrazyK86** [comment]
Hello,
Sorry for the late answer. Yes, the aggregation has changed again and again. We have now solved it in such a way that we always query all aggregations. This way we have no more gaps in the data.
