### ISSUE TITLE
Question: Multiple Splunk Forwarders with addon, avoiding duplicate data

### ISSUE THREAD

**Issue by tiny-dancer** [Microsoft/AzureMonitorAddonForSplunk#48]
When setting up multiple splunk forwarders with the addon, how is it recommended to configure event hub, plugin, splunk, etc to avoid sending duplicate data to splunk?

**Comment by sebastus** [comment]
Each resource sends its telemetry to a single event hub. Each event hub
gets configured to one forwarder.

**Comment by tiny-dancer** [comment]
Sounds good, that covers persistent runtime.  What is the recommendation when deploying updates to the forwarder to ensure no data loss or duplication?  

in normal operation i would imagine a rolling or blue/green deploy, in both cases multiple forwarders will temporary be configured to one forwarder.  According to your above statement, is there a different recommendation?

**Comment by sebastus** [comment]
When an event hub successfully transmits its data, an internal pointer is
bumped. If the data is not transmitted, the internal pointer stays put. So
if you shut down a forwarder that is listening to a hub, that hub doesn't
lose any data or its place in the stream of data points. So - switch off
the add-on, let the forwarder drain, shut down/update, etc.

**Comment by russjury** [comment]
@sebastus - (I work with @tiny-dancer, so we're inquiring about the same issue) -- I get the concepts of the queue keeping track of where clients left off, but if I have one client (splunk forwarder/addon) that is replaced by a completely new instance of a client (splunk forwarder/addon) - because I'm rebuilding the VM rather than upgrading it - how does the event hub know to pick up where it left off with the old client, rather than assuming this is a completely unrelated client and starting it at the beginning of the queue?  Does the add-on have the concept of a 'Client ID/group' or something that is hardcoded, and thereby the same for all instances of it?

**Comment by sebastus** [comment]
There is a checkpoint file associated with the add-on.

If you switch to debug messages in ExecProcessor, you'll see a message
starting with "Checkpoint file name is: ".

Be careful about shut down of a forwarder that you're going to replace with
another, and copying the checkpoint file from the old to the new. If the
checkpoint gets out of sequence, the message stream from that hub will stop
because of the mismatch.

RELATED TOPIC:

There is an Azure Functions approach to this. The function sends telemetry
directly to the HEC port of Splunk boxes or Splunk Cloud. This avoids the
problem with the checkpoints, etc.

https://github.com/sebastus/AzureFunctionforSplunkVS

**Comment by russjury** [comment]
Thanks for the info @sebastus.  Much appreciated!
