### ISSUE TITLE
Sourcetype naming convention

### ISSUE THREAD

**Issue by cygnetix** [Microsoft/AzureMonitorAddonForSplunk#53]
Any chance that you might reconsider the sourcetype names?

Generally the rule of thumb is to use _vendor:product_ and something that's descriptive. I think that the use of _amal:activityLog_ isn't particularly obvious as to what it is (or at least it wasn't to me). The use of a capital is also not something I've seen done and appending the word "Log" to the end of the sourcetype name is probably superfluous in any case (everything in Splunk is a log).

What do you think of these instead?
* ms:azure:diag
* ms:azure:activity
* ms:azure:metrics

This aligns with the sourcetypes used in the Azure AD Splunk TA (ms:aad:signin and ms:aad:audit) and the two O365 TAs that are available on splunkbase (ms:o365:management and ms:o365:reporting:messagetrace).

Also, thanks very much for the work done to create this TA. Getting good logging out of Azure has been pretty confusing but I feel like the Monitoring Service (plus EventHubs to export) is the direction things are going and I look forward to seeing this TA progress to the point that it's easy to set up and use.

**Comment by sebastus** [comment]
I put the sourcetype names into a json file so they're available to the user for configuration. The only exception are those coming from Activity Logs because the rules for assigning the sourcetype are so arcane for legacy reasons. Check out logCategories.json for the ones associated with Diagnostic Logs. Changing the ones associated with Activity Logs is a trivial fix to the source code. Look at line 287 in azure_monitor_logs.js. amal means "azure monitor activity logs", amdl means "azure monitor diagnostic logs" and amm means "azure monitor metrics". But change them to whatever you want. 

You might also be interested in the Azure Function approach to the problem of getting telemetry from Azure to Splunk. Check this out: https://github.com/microsoft/AzureFunctionForSplunkVS.
