### ISSUE TITLE
Conflict with DB Connect App?

### ISSUE THREAD

**Issue by vandersv** [microsoft/AzureMonitorAddonForSplunk#56]
Hi

Installing the TA-Azure_Monitor on the same machine as the Splunk DB Connect App (3.1.3) causes a conflict. The DB Connect app throws this error:

`<?xml version="1.0" encoding="UTF-8"?> <response> <messages> <msg type="WARN">Traceback (most recent call last): File "/opt/splunk/bin/rest_handler.py", line 79, in &lt;module&gt; print splunk.rest.dispatch(**params) File "/opt/splunk/lib/python2.7/site-packages/splunk/rest/__init__.py", line 149, in dispatch module = __import__('splunk.rest.external.%s' % parts[0], None, None, parts[0]) File "/opt/splunk/etc/apps/splunk_app_db_connect/bin/dbxproxy.py", line 7, in &lt;module&gt; from dbx_settings import Settings File "/opt/splunk/etc/apps/splunk_app_db_connect/bin/dbx_settings.py", line 10, in &lt;module&gt; import splunklib.client as client File "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/splunklib/__init__.py", line 18, in &lt;module&gt; from splunklib.six.moves import map ImportError: No module named six.moves </msg> </messages> </response>`

I logged a support ticket with Splunk and got the following response:

> I have tested another 3rd party app(TA-Proofpoint-TAP) which showed similar symptom and noticed that $APP_HOME/bin/splunklib folder caused the current symptom, 

> I have been able to make this work either by removing the app or by removing read/write permission from $APP_HOME/bin/splunklib folder(i.e chmod 000 $APP_HOME/bin/splunklib).  

> As TA-Azure_monitor app is not supported by Splunk, can you kindly contact developers for TA-Azure_monitor app and change $APP-HOME/bin/splunklib folder name for the app structure so that there is no naming conflict?

For now, I'm going to run TA-Azure_Monitor on a separate Splunk server, but am keen to know how to solve this properly.

Thanks,
Matt

**Comment by sebastus** [comment]
Looks like db connect is using the instance of splunklib installed in the azure monitor add-on's folders: import splunklib.client as client File "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/splunklib/__init__.py. that seems wrong.

**Comment by sebastus** [comment]
@droodleskins Did they say anything about why?

**Comment by droodleskins** [comment]
On DB Connect WebUI, we saw the following error and I noticed that this issue happens due to conflict between DB Connect app and TA-Azure_Monitor app. 
== 
<?xml version="1.0" encoding="UTF-8"?> <response> <messages> <msg type="WARN">Traceback (most recent call last): File "/opt/splunk/bin/rest_handler.py", line 79, in &lt;module&gt; print splunk.rest.dispatch(**params) File "/opt/splunk/lib/python2.7/site-packages/splunk/rest/__init__.py", line 149, in dispatch module = __import__('splunk.rest.external.%s' % parts[0], None, None, parts[0]) File "/opt/splunk/etc/apps/splunk_app_db_connect/bin/dbxproxy.py", line 4, in &lt;module&gt; import requests File "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/requests/__init__.py", line 43, in &lt;module&gt; import urllib3 ImportError: No module named urllib3 </msg> </messages> </response>
==

o We checked the installation time for TA-Azure_Monitor app which showed around 09-Nov at similar time the current issue was started.

**Comment by sebastus** [comment]
Where is splunklib installed? In the newest version, the am_depends file
puts it in the folder local to the add-on, rather than in SITE_PACKAGES.
Maybe this would be a good workaround?

**Comment by MikaJustas** [comment]
Is the solution for this in place or any timeline one the solution implementation?

**Comment by sebastus** [comment]
for my part, I'm still exploring the problem. I suggested a possible
solution, but haven't heard if it was successful or not.

**Comment by MikaJustas** [comment]
just tested, it fails. If this will require to deploy an additional HF it will be painful.

**Comment by sebastus** [comment]
Matt - still want to try to figure this out? Let me know. I'll get on the
phone with you.

**Comment by lowell80** [comment]
Has anyone confirmed that this still a problem with DB connect 3.1.4?

I'm wondering if DBX-4623 fixed the issue.   https://docs.splunk.com/Documentation/DBX/3.1.4/ReleaseNotes/Releasenotes
