### ISSUE TITLE
Question: Are there any plans to get this working for Splunk Cloud?

### ISSUE THREAD

**Issue by ghost2389** [Microsoft/AzureMonitorAddonForSplunk#71]
We are currently looking at deploying this tool as we are heavily invested in Azure and the ability of this add-on will help tremendously. However whenever we attempt to install this on the cloud it fails. Just curious if this is on the roadmap?

**Comment by sebastus** [comment]
@ghost2389 Love the interest in the add-on. Thank you. Splunk has a policy that only Splunk-certified apps can be installed in Splunk Cloud. They will only certify apps that include all dependencies in the package. I cannot include these dependencies due to legal concerns where I work. Sorry! Please take a look at the Azure Function that I wrote: https://github.com/Microsoft/AzureFunctionforSplunkVS. It does the same thing as the add-on but is much easier to install and works great with Splunk Cloud.
