### ISSUE TITLE
Method GET does not allow operation

### ISSUE THREAD

**Issue by Benthewater** [Microsoft/AzureMonitorAddonForSplunk#87]
Has anyone encounter this issue:

ERROR ExecProcessor - message from "/opt/splunk/etc/apps/TA-Azure_Monitor/bin/azure_activity_log.sh" Modular input azure_activity_log://Azure Activity Log Error getting event hub creds: StatusCodeError: 400 - {"error":{"code":"BadParameter","message":"Method GET does not allow operation 'e2ae3370f0b418e8cf3c6109d054497'"}}

Thanks in advance!

**Comment by sebastus** [comment]
Doesn't ring a bell. Are you using MSI creds or service principal? This has something to do with accessing key vault.

**Comment by Benthewater** [comment]
I will close this as it was resolved after rebuilding the credentials at Azure end. Thanks!

**Comment by anasamer** [comment]
@Benthewater 

Could you help and advise what did you enter for the required values below 

im so confused with the naming used in this Add-Od, mainly the last 3 items, are they for the event hub or for the key vault of the azure subscription   

SPNTenantID
SPNApplicationId
SPNApplicationKey
eventHubNamespace
vaultName
secretName
secretVersion

**Comment by sebastus** [comment]
The vaultName is the name of your key vault. The secretName is the name of
the secret containing the access policy for the event hub and the name of
that policy (in the content type property). The secret version is the
version number of that secret.

All of these details are in the wiki of the repo.

If you're ok with using an Azure Function rather than using the TA, it's
much simpler to implement.

https://github.com/microsoft/AzureFunctionforSplunkVS
